# Percorsi principali
dataset_dir: DataSet/cv-corpus-18.0-2024-06-14/it
phonemized_dir: output/
mel_output_dir: output/mel_segments/

# Parametri audio / mel
sr: 16000
n_fft: 400
hop_length: 160
n_mels: 80
top_db: 30  # trimming energia

# Parametri per target frame-level
phoneme_separator: "|"
max_frames: null
pad_mode: repeat

# Parametri modello (opzionali)
label_smoothing: 0.0

